DFDC_DATA_PATH: "/kaggle/input/deepfake-detection-challenge"
ARTIFACTS_PATH: "/kaggle/solution/artifacts"
MODELS_PATH: "/kaggle/solution/models"
SUBMISSION_PATH: "/kaggle/solution/output/submission.csv"
SUBMISSION_PATH_380: "/kaggle/solution/output/submission380.csv"
SUBMISSION_PATH_416: "/kaggle/solution/output/submission416.csv"
SUBMISSION_PATH_380V2: "/kaggle/solution/output/submission380v2.csv"
SUBMISSION_PATH_380V2_MID: "/kaggle/solution/output/submission380v2/submission380_{}.csv"
SUBMISSION_PATH_416_MID: "/kaggle/solution/output/submission416/submission416_{}.csv"